### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by kying-kear** [IAAR-Shanghai/Meta-Chunking#2]
当我按照流程部署启动项目后 在页面中Click to Chunking  后台报错：IndexError: The shape of the mask [507] at index 0 does not match the shape of the indexed tensor [0, 2] at index 0

**Comment by Robot2050** [comment]
![32564](https://github.com/user-attachments/assets/22bc1b0e-3373-425c-b18c-281c6da85bdf)
您尝试使用如下命令运行一下。同时先确保您使用的是Qwen，目前我们在方法实现上主要测试了Qwen2、Baichuan2。虽然方法与模型无关，但实现细节上略有差异。如果环境安装成功的话，应该是可以成功运行的，如上图所示。
CUDA_VISIBLE_DEVICES=0 python app.py
如果您还是不能运行，我将继续帮您解决！

**Comment by kying-kear** [comment]
我按照您的方法还是一样的错报。我在app.py中替换了

**Comment by kying-kear** [comment]
模型我使用的 Qwen2-1.5b-Instruct 我按照您的方法运行还是一样的报错。
我在app.py中只修改过一个地方 :
#from transformers import AutoModelForCausalLM, AutoTokenizer
from modelscope import AutoModelForSequenceClassification, AutoTokenizer不知道有没有影响

**Comment by kying-kear** [comment]
模型我使用的 Qwen2-1.5b-Instruct 我按照您的方法运行还是一样的报错。
我在app.py中只修改过一个地方 :
#from transformers import AutoModelForCausalLM, AutoTokenizer
from modelscope import AutoModelForSequenceClassification, AutoTokenizer不知道有没有影响

**Comment by Robot2050** [comment]
如果您希望用modelscope来加载模型的话，您可以使用如下代码导入，我测试之后也没有问题。
from modelscope import AutoModelForCausalLM, AutoTokenizer

**Comment by kying-kear** [comment]
ok 多谢！

**Comment by Robot2050** [comment]
好的，感谢您对我们工作的关注！
