### ISSUE TITLE
与Longbench的性能比较

### ISSUE THREAD

**Issue by TankNee** [IAAR-Shanghai/Meta-Chunking#6]
看了下论文里的性能表格，跟longbench论文里的检索性能表格，看起来差距有点大啊，而且我看meta-chunk的论文里用的是qwen2-7b，理应比longbench里面那几个模型要好一些，请问这块有找到原因吗？

![image](https://github.com/user-attachments/assets/3dd9c1fe-fede-45ac-9b12-7aa51f1f96c7)

**Comment by Robot2050** [comment]
感谢您对本工作的关注和提问！上述差异是由于两个工作希望测试的内容不一样，从而实验设置完全不一样导致的。LongBench 中的实验是为了测试不同大模型处理长文本的能力，在实验中他们整理数据集时将一个问题所有相关的文本段整合到一起，然后将所有信息传给大模型进行问答。
我们的实验是为了测试不同分块的效果，所以我们将他们整合好的长文本通过不同方法进行分块（严格控制变量，我们的实验的唯一变量就是不同的分块方法），同时将**一个数据集的所有分块混合在一起**进行检索增强生成（检索时设置top_k=5）。所以我们只是使用了该Benchmark的数据集和评估方法，并不存在可比性。
另外，在我们的实验流程中，主要是探索不同分块方法的差异，所以对于RAG的其他模块均没有使用当前最优的策略。所以上述对比也不能说明RAG性能不敌大模型长文本处理性能。
综上，我们的方法只是为您的RAG系统提供了一个更好的分块方法。为了追求最优的性能，您可以将meta-chunking与当前最优的RAG系统结合使用，综合提高您的系统性能。

**Comment by TankNee** [comment]
了解了谢谢。
