### ISSUE TITLE
论文中有个疑问想请教一下

### ISSUE THREAD

**Issue by Haitons** [IAAR-Shanghai/Meta-Chunking#8]
公式1
![image](https://github.com/user-attachments/assets/29dab0bb-32ab-47bf-9a3d-62f0118614f6)
where K represents the total number of tokens in xi, ti k denotes the k-th token in xi, and t<i signifies all tokens that precede xi.
论文中计算句子困惑度的公式，对于每个句子xi的PPL是基于之前所有句子t<i的tokens 来计算的。
而代码中：
first_cluster_ppl.append(loss[index:index + len_sentences[i]].mean().item())
当前句子的困惑度只考虑了该句子长度的token，并没有考虑之前句子，这个是什么原因呢？还是说我的理解有偏差，希望得到您的回复

**Comment by Robot2050** [comment]
感谢您对本工作的关注并提出有建设性的问题，很高兴为您解答！您可以先通过整理好的tools目录下的usage_lmchunker.ipynb、ppl_chunking.py和margin_sampling_chunking.py文件对我们的方法代码进行进一步的了解。因为论文里的代码由于要处理多个数据集可能不够清晰，您可以先通过这几个文件熟悉方法代码之后再去看论文用到的代码。

在ppl_chunking.py中，llm_chunker_ppl函数是入口，里面分了两种情况（图1）。如果文本长度较短，就直接将整个文段传入模型，计算出每句话的ppl值。这个过程中，计算下一个token的概率是基于上下文的（extract_by_html2text_db_nolist函数，图2）。如果文章长度较长，则是启用kv缓存机制，计算下一个token的概率利用切割后的部分上下文（extract_by_html2text_db_bench函数，图3）。
![image](https://github.com/user-attachments/assets/528d47cd-a27b-44c2-ad96-08475ab85d08)
![image](https://github.com/user-attachments/assets/ff07c7d1-1b6b-4ae6-b03c-c54a77481919)
![image](https://github.com/user-attachments/assets/9e4449c5-1be8-40c5-861f-5b7cad9bced1)

**Comment by Robot2050** [comment]
对于您指出来的这行代码，我没有定位到具体位置，您能给一下具体位置吗？欢迎您与我们更多的沟通交流！
first_cluster_ppl.append(loss[index:index + len_sentences[i]].mean().item())

**Comment by Robot2050** [comment]
刚刚定位到了您说的这行代码。这行代码是在计算完每个token的ppl值之后，为每个句子计算ppl值。在为每个token计算ppl值的时候是考虑到了上下文的，就如前面的图2和图3所示。这样再计算出来的句子的ppl值也就考虑到了前面的语言逻辑关系。

**Comment by Haitons** [comment]
> 感谢您对本工作的关注并提出有建设性的问题，很高兴为您解答！您可以先通过整理好的tools目录下的usage_lmchunker.ipynb、ppl_chunking.py和margin_sampling_chunking.py文件对我们的方法代码进行进一步的了解。因为论文里的代码由于要处理多个数据集可能不够清晰，您可以先通过这几个文件熟悉方法代码之后再去看论文用到的代码。
> 
> 在ppl_chunking.py中，llm_chunker_ppl函数是入口，里面分了两种情况（图1）。如果文本长度较短，就直接将整个文段传入模型，计算出每句话的ppl值。这个过程中，计算下一个token的概率是基于上下文的（extract_by_html2text_db_nolist函数，图2）。如果文章长度较长，则是启用kv缓存机制，计算下一个token的概率利用切割后的部分上下文（extract_by_html2text_db_bench函数，图3）。
> 
> 针对论文中不同数据集我们用到的ppl方法的时候，均采用的这两个函数名：extract_by_html2text_db_nolist、extract_by_html2text_db_bench。这两段代码的主要逻辑和区别是：一个是直接将整个文本传给模型；另一个是文本长度太长，需要利用KV机制适当的对文本进行剪切，不能完全考虑到所有的上下文。
> 
> 图1 ![image](https://private-user-images.githubusercontent.com/119649807/391311347-528d47cd-a27b-44c2-ad96-08475ab85d08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMzk4ODQsIm5iZiI6MTczMzEzOTU4NCwicGF0aCI6Ii8xMTk2NDk4MDcvMzkxMzExMzQ3LTUyOGQ0N2NkLWEyN2ItNDRjMi1hZDk2LTA4NDc1YWI4NWQwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMlQxMTM5NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYzljZjQ2OGFmYzMwODMwNjk1ZDk2ZTZlOWJjZDAxZjQ3ZWE3OGFiODczOGVlZTllNmI5YTA0NmQyZGVkMDU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lD1K3Crl4xfQ_yrt9qRFidxsmcIRfhzABZhSXTlMgkY) 图2 ![image](https://private-user-images.githubusercontent.com/119649807/391311353-ff07c7d1-1b6b-4ae6-b03c-c54a77481919.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMzk4ODQsIm5iZiI6MTczMzEzOTU4NCwicGF0aCI6Ii8xMTk2NDk4MDcvMzkxMzExMzUzLWZmMDdjN2QxLTFiNmItNGFlNi1iMDNjLWM1NGE3NzQ4MTkxOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMlQxMTM5NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZmZlYTgzNTdkNTIxZDhlNjI4ZGQ0MTIyOTgwM2QwYTdhZjhiNDFmZjQ4OTZlNTE4NTA0ZjUwYWFlZDAwYzY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3ynGTKvBh5OTxXOyiKuwSPhXv2InmqBf8iIahggU2aE) 图3 ![image](https://private-user-images.githubusercontent.com/119649807/391311363-9e4449c5-1be8-40c5-861f-5b7cad9bced1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMzk4ODQsIm5iZiI6MTczMzEzOTU4NCwicGF0aCI6Ii8xMTk2NDk4MDcvMzkxMzExMzYzLTllNDQ0OWM1LTFiZTgtNDBjNS04NjFmLTViN2NhZDliY2VkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMlQxMTM5NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZWExMzdlMDJkM2NlZTRiNjEwY2FjMjdlOTliYTMwNTY4YWU4OTQ3YmRjYTYxNGFlZGExZDYwODkzODYzYzFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GGkhKL1HmrDqEVUynym5ScEBf899ntSryAVcMpLVl_M)

感谢回复，之前看的是app.py中meta_chunking函数，这里面的ppl chunking只有extract_by_html2text_db_nolist
